parameters:
  - schema:
      type: string
    name: productId
    in: path
    required: true
post:
  summary: Create Draft
  tags:
    - Products
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../responses/ProductResponse.yaml'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '../../global/responses/ApiError.yaml'
  operationId: post-products-id-drafts
  description: Create a draft product from an existing product.
get:
  summary: Create draft
  tags:
    - Products
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../responses/ProductResponse.yaml'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '../../global/responses/ApiError.yaml'
  operationId: get-products-productId-drafts
  description: |-
    Create a draft for a product.

    If a draft already exists, that current draft will be returned.
