title: ProductCollection
allOf:
  - type: object
    properties:
      data:
        type: array
        items:
          $ref: '../models/Product.yaml'
  - type: object
    properties:
      meta:
        type: object
        $ref: '../../global/models/Pagination.yaml'
